---
- hosts:
    - server1
  tasks:
    - name: Installing rsync
      ansible.builtin.apt:
        pkg:
          - rsync
        update_cache: true
      tags:
        - initialization
        - dependecies_install

    - name: Installing apache2
      ansible.builtin.apt:
        pkg:
          - apache2
        update_cache: true
      tags:
        - initialization
        - dependecies_install
        - apache

    - name: Install Python pip
      apt: name={{ item }} update_cache=true state=present force_apt_get=yes
      with_items:
        - python3-pip
      become: true
      tags:
        - initialization
        - dependecies_install

    - name: Install pip
      ansible.builtin.pip:
        name: bottle
        state: forcereinstall
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Installing spacy
      ansible.builtin.pip:
        name: spacy
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip
  
    - name: Installing unidecode
      ansible.builtin.pip:
        name: unidecode
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Installing stop-words
      ansible.builtin.pip:
        name: stop-words
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Installing pyyaml
      ansible.builtin.pip:
        name: pyyaml
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Installing bs4
      ansible.builtin.pip:
        name: bs4
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Installing pandas
      ansible.builtin.pip:
        name: pandas
        executable: pip
      tags:
        - initialization
        - dependecies_install
        - pip

    - name: Load data configuration for data_path_source in the anm pc and data_path_destination for the server 
      ansible.builtin.include_vars: config_data.yml
      tags:
        - initialization
        - load_playbook_conf_data

    - name: Load config vars to check if download EN template
      ansible.builtin.include_vars: "{{ config_path_source }}"
      tags:
        - initialization
        - load_python_project_conf_data

    - name: downloading EN template for model
      ansible.builtin.shell:
        cmd: python3 -m spacy download en_core_web_sm
        chdir: /home
      when: lang == "EN"
      tags:
        - initialization
        - dependecies_install

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: 'https://github.com/MandyMF/BabelMatcherTFM.git'
        dest: "{{ data_path_destination }}"
        clone: yes
        update: yes
      tags:
        - copying_data_to_server

    - name: Copy python code to pc
      ansible.posix.synchronize:
        src: "{{ config_path_source }}"
        dest: "{{ data_path_destination }}"
        mode: push
      tags:
        - copying_data_to_server

    - name: Check if data file already exists
      ansible.builtin.stat:
        path: "{{ data_path_destination }}/{{ data_to_process_path }}"
      register: data_file_already_exists
      tags:
        - copying_data_to_server
        - checking existence

    - name: Create placeholder data file
      ansible.builtin.file:
        path: "{{ data_path_destination }}/{{ data_to_process_path }}"
        state: directory
        mode: 755
      tags:
        - copying_data_to_server
        - creating_subdirs_to_file
      when: not data_file_already_exists.stat.exists

    - name: Delete placeholder data file
      ansible.builtin.file:
        path: "{{ data_path_destination }}/{{ data_to_process_path }}"
        state: absent
        mode: 755
      tags:
        - copying_data_to_server
        - deleting_dir_with_filename_created_avobe
      when: not data_file_already_exists.stat.exists

    - name: Copy data to the remote from source
      ansible.posix.synchronize:
        src: "{{ data_path_source }}"
        dest: "{{ data_path_destination }}/{{ data_to_process_path }}"
        mode: push
      tags:
        - copying_data_to_server

    - name: execute test script
      ansible.builtin.shell:
        cmd: python3 ./process_by_id_list_with_padchest_data.py
        chdir: "{{ data_path_destination }}"
      tags:
        - running_project

    - name: fetch results
      ansible.builtin.fetch:
        src: "{{ data_path_destination }}/{{ result_file_path }}"
        dest: "{{ result_from_model_destination_local }}/{{ inventory_hostname }}/id_list/{{ result_file_name_on_local }}"
        flat: yes
      tags:
        - fetch_results
    
    - name: fetch results html
      ansible.builtin.fetch:
        src: "{{ data_path_destination }}/{{ save_html_view }}"
        dest: "{{ result_from_model_destination_local }}/{{ inventory_hostname }}/id_list/{{ result_html_name_on_local }}"
        flat: yes
      tags:
        - fetch_results

    - name: mount html results in apache
      ansible.posix.synchronize:
        src: "{{ result_from_model_destination_local }}/{{ inventory_hostname }}/id_list/{{ result_html_name_on_local }}"
        dest: "/var/www/html/index.html"
        mode: push
      tags:
        - publish_data_with_apache